# Generated by Django 5.2.1 on 2025-06-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofessor',
            name='temas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temas_professor', to='accounts.tema'),
        ),
    ]
