# Generated by Django 5.2.1 on 2025-06-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_perfilprofessor_temas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilprofessor',
            name='temas',
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='temas',
            field=models.ManyToManyField(related_name='temas_professor', to='accounts.tema'),
        ),
    ]
