# Generated by Django 5.2.1 on 2025-06-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_perfilprofessor_temas_perfilprofessor_temas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilprofessor',
            name='formacao',
        ),
    ]
