# Generated by Django 5.2.1 on 2025-06-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_perfilprofessor_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofessor',
            name='apresentacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilprofessor',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
