# Generated by Django 5.2.1 on 2025-06-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_aula_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=10),
        ),
    ]
