# Generated by Django 5.2.1 on 2025-06-30 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_aula_status'),
        ('pagamentos', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='pago',
        ),
        migrations.AddField(
            model_name='aula',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='pagamentos.pagamento'),
        ),
    ]
